---
apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: argocd-github-cluster-apps
spec:
  generators:
    - matrix:
        generators:
          - clusters: {}
          - scmProvider:
              github:
                organization: pthornton-argocd
                allBranches: false
                tokenRef:
                  secretName: creds-2073913259
                  key: token
              cloneProtocol: ssh
              filters:
              - repositoryMatch: ^*
                pathsExist: [helm,catalog-info.yaml]
                labelMatch: argocd-dev
  template:
    metadata:
      name: '{{ repository }}'
    spec:
      project: default
      source:
        repoURL: '{{ url }}'
        targetRevision: '{{ branch }}'
        path: helm
        helm:
          parameters:
          - name: 'server'
            value: '{{server}}'
          - name: 'organization'
            value: '{{ organization }}'
          - name: 'repository'
            value: '{{ repository }}'
          - name: 'url'
            value: '{{ url }}'
          - name: 'branch'
            value: '{{ branch }}'
          - name: 'sha'
            value: '{{ sha }}'
          - name: 'short_sha'
            value: '{{ short_sha }}'
          - name: 'labels'
            value: '{{ labels }}'
      destination:
        server: '{{server}}'
        namespace: '{{ repository }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}
