---
apiVersion: v1
kind: Secret
metadata:
  name: guestbook-test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: "git@github.com:pthornton/guestbook-test.git"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        helm:
          parameters:
          - name: "custom1"
            value: "custom value 1"
          - name: "custom2"
            value: "custom value 2"
          - name: "custom3"
            value: "custom value 3"
        repoURL: "git@github.com:pthornton/guestbook-test.git"
        targetRevision: HEAD
        path: helm
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}

